#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'game'

SNAKES = {
  14 => 4,
  19 => 8,
  22 => 20,
  24 => 16
}.freeze

LADDERS = {
  3 => 11,
  6 => 17,
  9 => 18,
  10 => 12
}.freeze

Game.new(snakes: SNAKES, ladders: LADDERS)
